openapi: 3.0.1
info:
  title: smile-topology-spec
  version: '1.0'
paths: {}
components:
  schemas:
    ChangeSetMember:
      type: object
      properties:
        $type:
          type: string
      additionalProperties: false
    DataSetMember:
      allOf:
        - $ref: '#/components/schemas/IdentifiedObject'
        - type: object
          properties:
            $type:
              type: string
            targetObject:
              type: string
            change:
              $ref: '#/components/schemas/ChangeSetMember'
            reverseChange:
              $ref: '#/components/schemas/ObjectReverseModification'
          additionalProperties: false
    EquipmentContainer:
      allOf:
        - $ref: '#/components/schemas/IdentifiedObject'
        - type: object
          properties:
            kind:
              $ref: '#/components/schemas/EquipmentContainerKind'
            wgs84longitude:
              type: number
              format: double
            wgs84latitude:
              type: number
              format: double
          additionalProperties: false
    EquipmentContainerKind:
      enum:
        - PrimarySubstation
        - SecondarySubstation
        - CableBox
        - Tower
      type: string
    IdentifiedObject:
      type: object
      properties:
        $type:
          type: string
        mRID:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    ObjectCreation:
      allOf:
        - $ref: '#/components/schemas/ChangeSetMember'
        - type: object
          properties:
            object:
              $ref: '#/components/schemas/IdentifiedObject'
              $type:
                type: string
          additionalProperties: false
    ObjectDeletion:
      allOf:
        - $ref: '#/components/schemas/ChangeSetMember'
        - type: object
          additionalProperties: false
    ObjectModification:
      allOf:
        - $ref: '#/components/schemas/ChangeSetMember'
        - type: object
          properties:
            modifications:
              type: array
              items:
                $ref: '#/components/schemas/PropertyModification'
                nullable: true
          additionalProperties: false
    ObjectReverseModification:
      allOf:
        - $ref: '#/components/schemas/ChangeSetMember'
        - type: object
          properties:
            modifications:
              type: array
              items:
                $ref: '#/components/schemas/PropertyModification'
                nullable: true
          additionalProperties: false
    PropertyModification:
      type: object
      properties:
        $type:
          type: string
        name:
          type: string
          nullable: true
        value:
          nullable: true
      additionalProperties: false
    TopologyDirectedLink:
      allOf:
        - $ref: '#/components/schemas/IdentifiedObject'
        - type: object
          properties:
            parent:
              type: string
            child:
              type: string
            switchStatus:
              $ref: '#/components/schemas/TopologyDirectedLinkSwitchStatusKind'
          additionalProperties: false
    TopologyDirectedLinkSwitchStatusKind:
      enum:
        - Normal
        - Actual
      type: string
    TopologyNode:
      allOf:
        - $ref: '#/components/schemas/IdentifiedObject'
        - type: object
          properties:
            equipmentContainer:
              type: string
            baseVoltage:
              type: integer
              format: int32
            kind:
              $ref: '#/components/schemas/TopologyNodeKind'
          additionalProperties: false
    TopologyNodeKind:
      enum:
        - ExternalNetworkInjection
        - PowerTransformer
        - BusbarSection
        - FeederBay
      type: string
    UsagePoint:
      allOf:
        - $ref: '#/components/schemas/IdentifiedObject'
        - type: object
          properties:
            topologyNode:
              type: string
          additionalProperties: false
